language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jpbodiong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jpbodiong/react-test npm test -- --coverage

after_success:
  - docker build -t jpbodiong/multi-client ./client
  - docker build -t jpbodiong/multi-nginx ./nginx
  - docker build -t jpbodiong/multi-server ./server
  - docker build -t jpbodiong/multi-worker ./worker
  # Log in to the docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jpbodiong/multi-client
  - docker push jpbodiong/multi-nginx
  - docker push jpbodiong/multi-server
  - docker push jpbodiong/multi-worker