name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin '${{ secrets.DOCKER_PASSWORD }}'
      # Use of --password-stdin instead of -p for: docker login
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - run: docker build -t jpbodiong/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jpbodiong/react-test npm test
 
      - run: docker build -t jpbodiong/multi-client-10-14 ./client
      - run: docker build -t jpbodiong/multi-nginx-10-14 ./nginx
      - run: docker build -t jpbodiong/multi-server-10-14 ./server
      - run: docker build -t jpbodiong/multi-worker-10-14 ./worker
 
      - run: docker push jpbodiong/multi-client-10-14
      - run: docker push jpbodiong/multi-nginx-10-14
      - run: docker push jpbodiong/multi-server-10-14
      - run: docker push jpbodiong/multi-worker-10-14