name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t jpbodiong/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true jpbodiong/react-test npm test
 
      - run: docker build -t jpbodiong/multi-client ./client
      - run: docker build -t jpbodiong/multi-nginx ./nginx
      - run: docker build -t jpbodiong/multi-server ./server
      - run: docker build -t jpbodiong/multi-worker ./worker
 
      - run: docker push jpbodiong/multi-client
      - run: docker push jpbodiong/multi-nginx
      - run: docker push jpbodiong/multi-server
      - run: docker push jpbodiong/multi-worker